name: Production Deploy To AWS Lambda

on:
  pull_request:
    branches: [ main ]
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7.2']

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@ee2113536afb7f793eed4ce60e8d3b26db912da4 # v1.127.0
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: false # runs 'bundle install' and caches installed gems automatically

      - name: Bundle install
        run: bundle install --path vendor/gems

      - name: Generate Environment Variables File for Production
        run: |
          echo "DB_HOST_PRODUCTION=$DB_HOST_PRODUCTION" >> .env.production
          echo "DB_PASSWORD_PRODUCTION=$DB_PASSWORD_PRODUCTION" >> .env.production
          echo "WORKNET_API_KEY=$WORKNET_API_KEY" >> .env.production
          echo "GOOGLE_PROJECT_ID=$GOOGLE_PROJECT_ID" >> .env.production
          echo "GOOGLE_CLIENT_EMAIL=$GOOGLE_CLIENT_EMAIL" >> .env.production
          echo "GOOGLE_PRIVATE_KEY=$GOOGLE_PRIVATE_KEY" >> .env.production
          echo "NAVER_API_KEY_ID=$NAVER_API_KEY_ID" >> .env.production
          echo "NAVER_API_KEY=$NAVER_API_KEY" >> .env.production
          echo "KAKAO_REST_API_KEY=$KAKAO_REST_API_KEY" >> .env.production
          echo "KAKAO_BIZMSG_PROFILE=$KAKAO_BIZMSG_PROFILE" >> .env.production
        env:
          DB_HOST_PRODUCTION: ${{ secrets.DB_HOST_PRODUCTION }}
          DB_PASSWORD_PRODUCTION: ${{ secrets.DB_PASSWORD_PRODUCTION }}
          WORKNET_API_KEY: ${{ secrets.WORKNET_API_KEY }}
          GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
          GOOGLE_CLIENT_EMAIL: ${{ secrets.GOOGLE_CLIENT_EMAIL }}
          GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
          NAVER_API_KEY_ID: ${{ secrets.NAVER_API_KEY_ID }}
          NAVER_API_KEY: ${{ secrets.NAVER_API_KEY }}
          KAKAO_REST_API_KEY: ${{ secrets.KAKAO_REST_API_KEY }}
          KAKAO_BIZMSG_PROFILE: ${{ secrets.KAKAO_BIZMSG_PROFILE }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2


      - name: Jets deploy
        env:
          JETS_ENV: production
        run: echo y | bundle exec jets deploy


      - name: Action Slack
        uses: 8398a7/action-slack@v3
        if: always()
        with:
          status: ${{ job.status }}
          author_name: PRODUCTION Deployment
          fields: repo,message,commit,author,action,eventName,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required