name: Use Firebase Admin JSON

on:
  push:
    branches:
      - staging-*

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Firebase Admin JSON
        run: |
          echo "Firebase Admin JSON: ${#FIREBASE_ADMIN_JSON}"
        env:
          FIREBASE_ADMIN_JSON: ${{ secrets.FIREBASE_ADMIN_JSON }}